title: 读书笔记
description: 小白龙的前端读书笔记
locales:
  /:
    lang: zh-CN
    title: 读书笔记
    description: 小白龙的前端读书笔记
head: 
  -
    - link
    -
      rel: icon
      href: /avatar.png
themeConfig :
  logo: /avatar.png
  nav:
    - text: 博客
      link: https://blog.xblcity.com
    - text: Github
      link: https://github.com/xblcity/reading-notes
  sidebar: 
    - title: 总览
      path: /
    - title: 前端书籍
      collapsable: false
      sidebarDepth: 2
      children:
        - /books/professional-javascript
        - /books/understanding-es6
        - /books/you-don't-know-js1
        - /books/understanding-node
        - /books/understanding-webpack
        - /books/node-in-action
        - /books/koa-in-action
    - title: 文档
      collapsable: false
      sidebarDepth: 2
      children:
        - /docs/react

    

    