title: 读书笔记
description: 小白龙的前端读书笔记
locales:
  /:
    lang: zh-CN
    title: 读书笔记
    description: 小白龙的前端读书笔记
head:
  - - link
    - rel: icon
      href: /avatar.png
plugins:
  - - "@vuepress/back-to-top"
  - - vuepress-plugin-helper-live2d
    - live2d:
        enable: true
        model: tororo
        display:
          position: right
          width: 150
          height: 300
          hOffset: 15
          vOffset: 60
        mobile:
          show: false
        react:
          opacity: 0.8
themeConfig:
  logo: /avatar.png
  nav:
    - text: 博客
      link: https://xblcity.github.io/blog
    - text: Github
      link: https://github.com/xblcity/reading-notes
  sidebar:
    - title: 总览
      path: /
    - title: :zzz:2020年
      collapsable: false
      sidebarDepth: 2
      children:
        - /books20/functional-javascript
        - /books20/react20
        - /books20/node-in-action
    - title: :zzz:2019年
      collapsable: false
      sidebarDepth: 2
      children:
        - /books19/professional-javascript
        - /books19/understanding-es6
        - /books19/you-don't-know-js1
        - /books19/understanding-node
        - /books19/understanding-webpack
        - /books19/react
        - /books19/vue
